FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY manage.py .
COPY config ./config
COPY core ./core
COPY expense_site ./expense_site
COPY expense_tracker ./expense_tracker
COPY templates ./templates
COPY static ./static
COPY expense_entrypoint.sh .

EXPOSE 8000
