from django.db import migrations, models
import django.db.models.deletion
import django.core.validators

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Account', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('key', models.CharField(max_length=30, unique=True)), ('title', models.CharField(max_length=100)), ('opening_balance', models.BigIntegerField(default=0))]),
        migrations.CreateModel(name='AppSetting', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('key', models.CharField(max_length=80, unique=True)), ('value', models.CharField(max_length=200)), ('label', models.CharField(max_length=120)), ('updated_at', models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Brand', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=50, unique=True)), ('active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='Color', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=50, unique=True)), ('code', models.CharField(blank=True, max_length=10)), ('active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='SaleDay', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('date', models.DateField(unique=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Size', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=20, unique=True)), ('sort_order', models.PositiveSmallIntegerField(default=0))], options={'ordering': ['sort_order', 'id']}),
        migrations.CreateModel(name='StockLocation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('key', models.CharField(choices=[('home', 'خانه'), ('khorshid', 'خورشید')], max_length=20, unique=True)), ('title', models.CharField(max_length=50))]),
        migrations.CreateModel(name='ProductCode', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('code', models.CharField(max_length=50)), ('pack_qty', models.PositiveIntegerField(default=1)), ('active', models.BooleanField(default=True)), ('note', models.CharField(blank=True, max_length=200)), ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.brand'))]),
        migrations.CreateModel(name='ProductComposition', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('qty', models.PositiveIntegerField(default=1)), ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.color')), ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='core.productcode'))]),
        migrations.CreateModel(name='ProductSize', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('default_sale_price', models.PositiveBigIntegerField(default=0)), ('unit_cost', models.PositiveBigIntegerField(default=0)), ('active', models.BooleanField(default=True)), ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.productcode')), ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.size'))]),
        migrations.CreateModel(name='SaleLine', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('quantity', models.PositiveIntegerField(default=0)), ('sale_price', models.PositiveBigIntegerField(default=0)), ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.saleday')), ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productsize'))]),
        migrations.CreateModel(name='Replacement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('qty', models.PositiveIntegerField()), ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='core.saleline')), ('source_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_sources', to='core.color')), ('target_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_targets', to='core.color'))]),
        migrations.CreateModel(name='StockBalance', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('qty', models.IntegerField(default=0)), ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.brand')), ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.color')), ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stocklocation')), ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.size'))]),
        migrations.CreateModel(name='StockThreshold', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('home_min', models.PositiveIntegerField(default=0)), ('total_min', models.PositiveIntegerField(default=0)), ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.brand')), ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.color')), ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.size'))]),
        migrations.CreateModel(name='InventoryMovement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('movement_type', models.CharField(choices=[('purchase', 'خرید'), ('sale', 'فروش'), ('transfer', 'انتقال'), ('production', 'تولید'), ('adjust', 'اصلاح')], max_length=20)), ('delta', models.IntegerField()), ('reference', models.CharField(blank=True, max_length=120)), ('created_at', models.DateTimeField(auto_now_add=True)), ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.brand')), ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.color')), ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stocklocation')), ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.size'))]),
        migrations.CreateModel(name='MoneyMovement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('date', models.DateField()), ('kind', models.CharField(choices=[('transfer', 'انتقال'), ('expense', 'خرج'), ('settlement', 'تسویه'), ('purchase', 'خرید'), ('receipt', 'دریافت')], max_length=30)), ('amount', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])), ('title', models.CharField(max_length=150)), ('affects_capital', models.BooleanField(default=False)), ('note', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_movements', to='core.account')), ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_movements', to='core.account'))]),
        migrations.AddConstraint(model_name='productcode', constraint=models.UniqueConstraint(fields=('brand', 'code'), name='uniq_brand_code')),
        migrations.AddConstraint(model_name='productcomposition', constraint=models.UniqueConstraint(fields=('product', 'color'), name='uniq_product_color')),
        migrations.AddConstraint(model_name='productsize', constraint=models.UniqueConstraint(fields=('product', 'size'), name='uniq_product_size')),
        migrations.AddConstraint(model_name='saleline', constraint=models.UniqueConstraint(fields=('day', 'product_size'), name='uniq_day_product_size')),
        migrations.AddConstraint(model_name='stockbalance', constraint=models.UniqueConstraint(fields=('brand', 'size', 'color', 'location'), name='uniq_stock_balance')),
        migrations.AddConstraint(model_name='stockthreshold', constraint=models.UniqueConstraint(fields=('brand', 'size', 'color'), name='uniq_stock_threshold')),
    ]
