from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


def seed_existing_sale_allocations(apps, schema_editor):
    SaleLine = apps.get_model("core", "SaleLine")
    ProductComposition = apps.get_model("core", "ProductComposition")
    SaleAllocation = apps.get_model("core", "SaleAllocation")
    StockLocation = apps.get_model("core", "StockLocation")
    home = StockLocation.objects.filter(key="home").first()
    if not home:
        return
    for line in SaleLine.objects.filter(inventory_applied_quantity__gt=0).iterator():
        if SaleAllocation.objects.filter(sale_line_id=line.id).exists():
            continue
        for comp in ProductComposition.objects.filter(product_id=line.product_size.product_id):
            qty = int(line.inventory_applied_quantity or 0) * int(comp.qty or 0)
            if qty:
                SaleAllocation.objects.create(sale_line_id=line.id, color_id=comp.color_id, location_id=home.id, qty=qty, is_replacement=False)


class Migration(migrations.Migration):
    dependencies = [("core", "0002_saleline_inventory_applied_quantity")]

    operations = [
        migrations.CreateModel(name="SaleSnapshot",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("unit_cost",models.PositiveBigIntegerField(default=0)),("pack_qty",models.PositiveIntegerField(default=0)),("digikala_fee_unit",models.PositiveBigIntegerField(default=0)),("updated_at",models.DateTimeField(auto_now=True)),("sale_line",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="snapshot",to="core.saleline"))]),
        migrations.CreateModel(name="ExpenseCategory",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=80,unique=True)),("active",models.BooleanField(default=True))]),
        migrations.CreateModel(name="SideAsset",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=120)),("value",models.PositiveBigIntegerField(default=0)),("note",models.TextField(blank=True)),("active",models.BooleanField(default=True)),("updated_at",models.DateTimeField(auto_now=True))],options={"ordering":["name"]}),
        migrations.CreateModel(name="SupplierAccount",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=100,unique=True)),("opening_balance",models.BigIntegerField(default=0,help_text="مثبت یعنی بدهی ما به تامین‌کننده")),("active",models.BooleanField(default=True))]),
        migrations.CreateModel(name="ElasticBalance",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=40,unique=True)),("warehouse_kg",models.DecimalField(decimal_places=3,default=Decimal("0"),max_digits=9)),("pedram_kg",models.DecimalField(decimal_places=3,default=Decimal("0"),max_digits=9)),("unit_cost",models.PositiveBigIntegerField(default=0))]),
        migrations.CreateModel(name="AccountEntry",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("delta",models.BigIntegerField()),("title",models.CharField(max_length=180)),("reference",models.CharField(blank=True,db_index=True,max_length=140)),("entry_type",models.CharField(blank=True,max_length=40)),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="entries",to="core.account"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="BankTransfer",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("amount",models.PositiveBigIntegerField(validators=[MinValueValidator(1)])),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("from_account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="bank_transfers_out",to="core.account")),("to_account",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="bank_transfers_in",to="core.account"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="DigikalaSettlement",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("amount",models.PositiveBigIntegerField(validators=[MinValueValidator(1)])),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="Expense",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("amount",models.PositiveBigIntegerField(validators=[MinValueValidator(1)])),("title",models.CharField(max_length=160)),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("category",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.expensecategory"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="PedramPayment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("amount",models.PositiveBigIntegerField(validators=[MinValueValidator(1)])),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="SupplierEntry",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("delta",models.BigIntegerField()),("title",models.CharField(max_length=160)),("reference",models.CharField(blank=True,max_length=140)),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("supplier",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="entries",to="core.supplieraccount"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="TakvinPayment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("amount",models.PositiveBigIntegerField(validators=[MinValueValidator(1)])),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="FabricRoll",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("code",models.CharField(max_length=40,unique=True)),("purchase_date",models.DateField()),("weight_kg",models.DecimalField(decimal_places=3,max_digits=9)),("price_per_kg",models.PositiveBigIntegerField(default=0)),("location",models.CharField(choices=[("warehouse","انبار"),("pedram","نزد پدرام"),("consumed","مصرف‌شده")],default="warehouse",max_length=20)),("supplier_name",models.CharField(blank=True,max_length=100)),("paid_from_mellat",models.BooleanField(default=True)),("finance_applied",models.BooleanField(default=False)),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("color",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.color"))],options={"ordering":["code"]}),
        migrations.CreateModel(name="ElasticMovement",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("kind",models.CharField(choices=[("purchase","خرید"),("transfer","تحویل به پدرام"),("consume","مصرف"),("adjust","اصلاح")],max_length=20)),("qty_kg",models.DecimalField(decimal_places=3,max_digits=9)),("unit_cost",models.PositiveBigIntegerField(default=0)),("note",models.TextField(blank=True)),("applied",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("elastic",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="movements",to="core.elasticbalance"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="InventoryAdjustment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("delta",models.IntegerField()),("note",models.TextField(blank=True)),("applied",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("brand",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.brand")),("color",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.color")),("location",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.stocklocation")),("size",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.size"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="ProductionBatch",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("code",models.CharField(max_length=50,unique=True)),("cut_date",models.DateField()),("expected_qty",models.PositiveIntegerField(default=0)),("elastic16_used_kg",models.DecimalField(decimal_places=3,default=Decimal("0"),max_digits=8)),("elastic25_used_kg",models.DecimalField(decimal_places=3,default=Decimal("0"),max_digits=8)),("elastic16_unit_cost",models.PositiveBigIntegerField(default=0)),("elastic25_unit_cost",models.PositiveBigIntegerField(default=0)),("closed",models.BooleanField(default=False)),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("fabric_roll",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="batches",to="core.fabricroll"))],options={"ordering":["-cut_date","-id"]}),
        migrations.CreateModel(name="ReturnRecord",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("qty",models.PositiveIntegerField(validators=[MinValueValidator(1)])),("refund_amount",models.PositiveBigIntegerField(default=0)),("add_back_inventory",models.BooleanField(default=True)),("note",models.TextField(blank=True)),("applied",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("product_size",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.productsize"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="SaleAllocation",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("qty",models.PositiveIntegerField()),("is_replacement",models.BooleanField(default=False)),("color",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.color")),("location",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.stocklocation")),("sale_line",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="allocations",to="core.saleline"))]),
        migrations.CreateModel(name="SaleShortage",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("qty",models.PositiveIntegerField()),("resolved",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("sale_line",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="shortages",to="core.saleline")),("source_color",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="sale_shortage_sources",to="core.color")),("target_color",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="sale_shortage_targets",to="core.color"))]),
        migrations.CreateModel(name="StockTransfer",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("qty",models.PositiveIntegerField(validators=[MinValueValidator(1)])),("note",models.TextField(blank=True)),("applied",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("brand",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.brand")),("color",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.color")),("from_location",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="manual_transfers_out",to="core.stocklocation")),("size",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.size")),("to_location",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="manual_transfers_in",to="core.stocklocation"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="TakvinPurchase",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("qty",models.PositiveIntegerField(validators=[MinValueValidator(1)])),("list_unit_price",models.PositiveBigIntegerField()),("discount_percent",models.DecimalField(decimal_places=2,default=Decimal("10"),max_digits=5)),("net_unit_price",models.PositiveBigIntegerField(default=0)),("total_cost",models.PositiveBigIntegerField(default=0)),("note",models.TextField(blank=True)),("applied",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("color",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.color")),("size",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.size"))],options={"ordering":["-date","-id"]}),
        migrations.CreateModel(name="ProductionReceipt",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("qty",models.PositiveIntegerField(validators=[MinValueValidator(1)])),("labor_total",models.PositiveBigIntegerField(default=0)),("applied",models.BooleanField(default=False)),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("batch",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="receipts",to="core.productionbatch")),("color",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.color")),("destination",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.stocklocation")),("size",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="core.size"))],options={"ordering":["-date","-id"]}),
        migrations.RunPython(seed_existing_sale_allocations,migrations.RunPython.noop),
    ]
