from django.urls import path

from . import business_tools_v14, business_tools_v21, business_tools_v22, calculator_v37, calendar_views, catalog_v5, daily_order_views_v8, daily_report_actions_v21, daily_report_v8, daily_views, dia_gallery_v45, digikala_views_v40, excel_dashboard, excel_sales, final_views, inventory_operations_v15, inventory_v20, material_report_v20, material_report_v21, material_report_v22, pricing_v7, report_v9, returns_v37, sale_brand_v19, settings_rules_v17, settings_stock_v5, takvin_v5, views

urlpatterns = [
    path("", excel_dashboard.dashboard, name="dashboard"),
    path("digikala/", digikala_views_v40.digikala_home, name="digikala"),
    path("digikala/summary/", digikala_views_v40.digikala_summary, name="digikala_summary"),
    path("digikala/orders/", digikala_views_v40.digikala_orders, name="digikala_orders"),
    path("digikala/products/", digikala_views_v40.digikala_products, name="digikala_products"),
    path("digikala/packages/", digikala_views_v40.digikala_packages, name="digikala_packages"),
    path("digikala/packages/<int:package_id>/", digikala_views_v40.digikala_package_detail, name="digikala_package_detail"),
    path("digikala/sales/", digikala_views_v40.digikala_sales, name="digikala_sales"),
    path("digikala/warehouse/", digikala_views_v40.digikala_warehouse, name="digikala_warehouse"),
    path("digikala/returns/", digikala_views_v40.digikala_returns, name="digikala_returns"),
    path("calendar/picker/", calendar_views.jalali_picker, name="jalali_picker"),
    path("sales/", daily_views.sale_calendar, name="sale_start"),
    path("sales/select/<int:jy>/<int:jm>/<int:jd>/", daily_views.select_sale_day, name="select_sale_day"),
    path("sales/<int:day_id>/", sale_brand_v19.sale_brand, name="sale_brand"),
    path("sales/<int:day_id>/dia-gallery/", dia_gallery_v45.dia_gallery_sales, name="dia_gallery_sales"),
    path("sales/<int:day_id>/report/", daily_report_v8.daily_report, name="daily_report"),
    path("sales/<int:day_id>/import-xlsx/", daily_order_views_v8.import_daily_orders, name="daily_order_import"),
    path("sales/<int:day_id>/<int:brand_id>/<int:size_id>/", daily_views.sale_size, name="sale_size"),
    path("sales/save/", excel_sales.sale_line_save, name="sale_line_save"),
    path("sales/shortage/<int:shortage_id>/resolve/", excel_sales.shortage_resolve, name="shortage_resolve"),
    path("sales/report-line/<int:line_id>/price/", daily_report_actions_v21.sale_price_update, name="daily_sale_price_update"),
    path("sales/report-line/<int:line_id>/delete/", daily_report_actions_v21.sale_line_delete, name="daily_sale_line_delete"),

    path("returns/", returns_v37.returns_home, name="returns"),
    path("returns/apply/", returns_v37.return_apply, name="return_apply"),

    path("report/", report_v9.report, name="report"),
    path("report/manual/", report_v9.manual_report_action, name="manual_report_action"),
    path("report/financial-summary/", business_tools_v14.financial_summary, name="financial_summary"),
    path("material-report/", material_report_v22.material_report, name="material_report"),
    path("material-report/<int:block_id>/save/", material_report_v22.material_block_save, name="material_block_save"),
    path("material-report/<int:block_id>/apply/", material_report_v22.material_block_apply_materials, name="material_block_apply"),
    path("material-report/<int:block_id>/apply-output/", material_report_v22.material_block_apply_output, name="material_block_apply_output"),
    path("material-report/<int:block_id>/unapply/", material_report_v20.material_block_unapply_materials, name="material_block_unapply"),
    path("material-report/<int:block_id>/delete/", material_report_v20.material_block_delete, name="material_block_delete"),
    path("takvin/", takvin_v5.takvin_excel, name="takvin"),

    path("payments/", business_tools_v22.payments, name="payments"),
    path("payments/add/", business_tools_v22.payment_add, name="payment_add"),
    path("payments/<int:payment_id>/edit/", business_tools_v22.payment_update, name="payment_update"),
    path("payments/<int:payment_id>/delete/", business_tools_v22.payment_delete, name="payment_delete"),
    path("payments/mellat/set/", business_tools_v21.mellat_set, name="mellat_set"),
    path("payments/receipts/add/", business_tools_v21.receipt_add, name="receipt_add"),
    path("payments/receipts/<int:receipt_id>/edit/", business_tools_v21.receipt_update, name="receipt_update"),
    path("payments/receipts/<int:receipt_id>/delete/", business_tools_v21.receipt_delete, name="receipt_delete"),
    path("calculator/", calculator_v37.calculator, name="calculator"),
    path("calculator/quote/", calculator_v37.calculator_quote, name="calculator_quote"),
    path("calculator/target-quote/", calculator_v37.calculator_target_quote, name="calculator_target_quote"),

    path("inventory/", inventory_v20.inventory, name="inventory"),
    path("inventory/color-model/add/", inventory_v20.add_color_model, name="inventory_add_color_model"),
    path("inventory/operations/", inventory_operations_v15.inventory_operations, name="inventory_operations"),

    path("materials/", final_views.materials, name="materials"),
    path("production/", final_views.production, name="production"),
    path("finance/", final_views.finance, name="finance"),
    path("expenses/", final_views.expenses, name="expenses"),
    path("assets/", final_views.assets, name="assets"),

    path("settings/", views.settings_home, name="settings_home"),
    path("settings/catalog/", catalog_v5.settings_catalog, name="settings_catalog"),
    path("settings/products/", pricing_v7.settings_products, name="settings_products"),
    path("settings/products/new/", views.settings_product_form, name="settings_product_new"),
    path("settings/products/<int:product_id>/", views.settings_product_form, name="settings_product_edit"),
    path("settings/stock/", settings_stock_v5.settings_stock, name="settings_stock"),
    path("settings/finance/", views.settings_finance, name="settings_finance"),
    path("settings/rules/", settings_rules_v17.settings_rules, name="settings_rules"),
]
